export const USER_TOKEN = 'USER_TOKEN'
export const USER_INFO = 'USER_INFO'
export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_CLEAR = 'USER_CLEAR'
export const CART_LIST = 'CART_LIST'
export const CART = 'CART'
